// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvTOYOyPQVzAPJUab7CifcUT4lz7MoGns',
    appId: '1:78900842782:web:b337c2b37d469ea3f7790f',
    messagingSenderId: '78900842782',
    projectId: 'fir-flutter-codelab-d7a1e',
    authDomain: 'fir-flutter-codelab-d7a1e.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-d7a1e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf25vZnxbLFlSuxJGcsihNmVchn-kDJN8',
    appId: '1:78900842782:android:de854c3a703688d9f7790f',
    messagingSenderId: '78900842782',
    projectId: 'fir-flutter-codelab-d7a1e',
    storageBucket: 'fir-flutter-codelab-d7a1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPTnt9IE9Bype-O6JFaSVbErNIeOIVRHI',
    appId: '1:78900842782:ios:c54d52f51ebd0bf5f7790f',
    messagingSenderId: '78900842782',
    projectId: 'fir-flutter-codelab-d7a1e',
    storageBucket: 'fir-flutter-codelab-d7a1e.appspot.com',
    iosClientId:
        '78900842782-6i4mcbofu6it1qorph38mvhfijknh2u6.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPTnt9IE9Bype-O6JFaSVbErNIeOIVRHI',
    appId: '1:78900842782:ios:c54d52f51ebd0bf5f7790f',
    messagingSenderId: '78900842782',
    projectId: 'fir-flutter-codelab-d7a1e',
    storageBucket: 'fir-flutter-codelab-d7a1e.appspot.com',
    iosClientId:
        '78900842782-6i4mcbofu6it1qorph38mvhfijknh2u6.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
